#!/usr/bin/env python3
"""
Automated performance measurement for LINPACK benchmark.
"""

import subprocess
import sys
import re
import time
import csv
import statistics
import argparse
import numpy as np
from pathlib import Path
Path("results").mkdir(exist_ok=True)
SCRIPT_DIR = Path(__file__).parent.resolve()

# Configuration
N_RUNS = 40
# Binary files
ORIG_BIN =  SCRIPT_DIR / "linpack"
LLVM_BIN =  SCRIPT_DIR / "llvm_linpack"
TIGRESS_BIN =  SCRIPT_DIR / "tigress_linpack"
VMPROTECT_BIN =  SCRIPT_DIR / "vmprotect_linpack"
THEMIDA_BIN =  SCRIPT_DIR / "themida_linpack_protected"

def run_benchmark(exe, N):
    """Run the benchmark with CPU affinity and high priority, return (time_seconds, mflops)."""
    # cmd: taskset + nice + linpack
    cmd = ['taskset', '-c', '0', 'nice', '-n', '-20', exe, str(N)]
    result = subprocess.run(cmd, capture_output=True, text=True)
    output = result.stdout + result.stderr
    time_match = re.search(r"Time in seconds\s*=\s*([0-9.eE+-]+)", output)
    mflops_match = re.search(r"MegaFLOPS\s*=\s*([0-9.eE+-]+)", output)
    if time_match and mflops_match:
        t = float(time_match.group(1))
        mf = float(mflops_match.group(1))
        return t, mf
    else:
        print("Failed to parse output:")
        print(output)
        return None, None

def measure(exe, runs, N):
    """Run benchmark multiple times, return list of (t, mf)."""
    results = []
    for i in range(runs):
        #print(f"  Run {i+1}/{runs}...")
        t, mf = run_benchmark(exe, N)
        if t is not None:
            results.append((t, mf))
        else:
            print("Skipping this run due to error.")
    return results

def save_csv(data, filename, labels):
    """Save results to CSV file."""
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Configuration", "Run", "Time(s)", "MFLOPS"])
        for label, runs in zip(labels, data):
            for i, (t, mf) in enumerate(runs):
                writer.writerow([label, i+1, t, mf])

def print_stats(data, labels):
    """Print statistics for each configuration."""
    for label, runs in zip(labels, data):
        times = [t for t,_ in runs]
        mflops = [mf for _,mf in runs]
        if times:
            print(f"\n{label}:")
            print(f"  Time: mean={statistics.mean(times):.9f}, std={statistics.stdev(times):.9f}s")
            print(f"  MFLOPS: mean={statistics.mean(mflops):.9f}, std={statistics.stdev(mflops):.9f}")
            median_time = np.median(times)
            median_mflops = np.median(mflops)
            print(f"  Time: median={median_time:.9f}s, IQR={np.percentile(times,75)-np.percentile(times,25):.9f}s")
            print(f"  MFLOPS: median={median_mflops:.9f}, IQR={np.percentile(mflops,75)-np.percentile(mflops,25):.9f}")

def analyze_csv(csv_path):
    """
    Read a CSV file generated by this script and print statistics.
    Expected columns: Configuration, Run, Time(s), MFLOPS
    """
    data = {}
    with open(csv_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            config = row['Configuration']
            if config not in data:
                data[config] = {'times': [], 'mflops': []}
            data[config]['times'].append(float(row['Time(s)']))
            data[config]['mflops'].append(float(row['MFLOPS']))
    
    print(f"Statistics from {csv_path}:\n")
    for config, values in data.items():
        times = values['times']
        mflops = values['mflops']
        if times:
            print(f"{config}:")
            print(f"  Time: mean={statistics.mean(times):.9f}s, std={statistics.stdev(times):.9f}s")
            print(f"  MFLOPS: mean={statistics.mean(mflops):.9f}, std={statistics.stdev(mflops):.9f}")
            median_time = np.median(times)
            median_mflops = np.median(mflops)
            print(f"  Time: median={median_time:.9f}s, IQR={np.percentile(times,75)-np.percentile(times,25):.9f}s")
            print(f"  MFLOPS: median={median_mflops:.9f}, IQR={np.percentile(mflops,75)-np.percentile(mflops,25):.9f}\n")

def warmup(exe, N, warmup_runs=10):
    for _ in range(warmup_runs):
        subprocess.run(['taskset', '-c', '0', 'nice', '-n', '-20', exe, str(N)], 
                       capture_output=True)

def main():
    for N in [100, 250, 500]:
        parser = argparse.ArgumentParser(description="LINPACK benchmark runner and analyzer")
        parser.add_argument('--analyze', metavar='CSV_FILE', help='Analyze an existing CSV file instead of running benchmarks')
        args = parser.parse_args()

        if args.analyze:
            analyze_csv(args.analyze)
            return
    
        LDA = N + 1
        # run measurements
        print("\nMeasuring original version...")
        warmup(ORIG_BIN, N, warmup_runs=10)
        orig_results = measure(ORIG_BIN, N_RUNS, N)
        print("\nMeasuring Tigress version...")
        warmup(TIGRESS_BIN, N, warmup_runs=10)
        tigress_results = measure(TIGRESS_BIN, N_RUNS, N)
        print("\nMeasuring VMProtect version...")
        warmup(VMPROTECT_BIN, N, warmup_runs=10)
        vmprotect_results = measure(VMPROTECT_BIN, N_RUNS, N)
        print("\nMeasuring Themida version...")
        warmup(THEMIDA_BIN, N, warmup_runs=10)
        themida_results = measure(THEMIDA_BIN, N_RUNS, N)
        print("\nMeasuring Softcom LLVM obfuscator version...")
        warmup(LLVM_BIN, N, warmup_runs=10)
        llvm_results = measure(LLVM_BIN, N_RUNS, N)

        # Save results
        all_results = [orig_results]
        labels = ["Original"]
        save_csv(all_results, "results/linpack_bench_results_orig_" + str(N) + ".csv", labels)

        # Print statistics
        print_stats(all_results, labels)

if __name__ == "__main__":
    main()
